<a href="https://colab.research.google.com/github/Ashmit990/AI-Worksheet-1/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1: Initialize an empty array with size 2X2.


In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)


[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


Question 2: Initialize an all one array with size 4X2.

In [ ]:
import numpy as np
all_one_array = np.ones((4,2))
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Question 3: Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np
fill_value = np.full((4,2),7)
print(fill_value)

[[7 7]
 [7 7]
 [7 7]
 [7 7]]


Question 4: Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np
array_of_zeros = np.zeros_like([[1,2,3],[4,5,6]])
print(array_of_zeros)

[[0 0 0]
 [0 0 0]]


Question 5: Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np
array_of_ones = np.ones_like([[2,1],[4,5]])
print(array_of_ones)

[[1 1]
 [1 1]]


Question 6: For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
new_list=[1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


Problem 2: Question 1: Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Question 2: Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}


In [ ]:
import numpy as np
array = np.arange(0,9)
reshaped_array = np.reshape(array,(3,3))
print(reshaped_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Question 3: Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 4: Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np
random_array = np.random.random(30)
mean = random_array.mean()
print('random array = ' , random_array)
print('mean = ' , mean)

random array =  [0.2978791  0.28964622 0.81394169 0.07704998 0.66585747 0.29407992
 0.6419471  0.00333207 0.27602045 0.65352935 0.55543438 0.72461325
 0.69552125 0.50174542 0.85048512 0.25697769 0.56984504 0.79653287
 0.81262755 0.47273752 0.53985275 0.71482577 0.32192067 0.3454868
 0.73397857 0.04215414 0.24916629 0.53935731 0.98427981 0.60541115]
mean =  0.5108745561759672


Question 5: Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np
random_arr = np.random.random((10, 10))
min_value = random_arr.min()
max_value = random_arr.max()
print('random array: ', random_arr)
print('min value: ', min_value)
print('max value: ', max_value)

random array:  [[2.64499119e-01 3.47838680e-01 9.04585785e-01 9.89672682e-01
  2.28891929e-01 7.90077490e-01 1.89143140e-01 6.45566223e-01
  5.12217361e-01 6.37020995e-01]
 [5.12130252e-01 5.44495049e-01 5.51822350e-01 3.66570369e-01
  7.06532976e-01 7.24811840e-01 4.58979260e-01 2.18131186e-01
  9.77365244e-03 6.31013918e-01]
 [4.77281643e-01 3.48108709e-01 1.49346533e-01 1.40915157e-01
  5.55715686e-01 4.57807323e-01 3.22598275e-01 1.77275469e-01
  3.75334571e-01 8.72979031e-01]
 [5.90381234e-02 3.40265018e-01 3.15860330e-01 4.76593144e-01
  9.35181967e-01 5.12928377e-02 6.92938161e-01 8.22090254e-01
  1.36113680e-01 9.99507292e-01]
 [7.99795804e-01 5.85283473e-02 2.94831085e-01 5.31173405e-02
  2.43931628e-01 1.06372358e-01 1.06198669e-01 2.49844606e-01
  1.95194973e-01 9.93885739e-01]
 [5.18111087e-01 6.32497790e-01 5.73338386e-01 5.54153733e-01
  4.44023749e-01 3.17179852e-01 6.74918214e-01 2.38640882e-01
  3.14021832e-01 9.33772116e-01]
 [6.21714322e-01 9.50043474e-01 5.38255562e

Question 6: Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Question 7: Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


Question 8: Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Question 9: Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3: Array Operations: For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2],[3, 5]])

y = np.array([[5, 6],[7, 8]])

result = x + y
print(result)



[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
result = x - y
print(result)

[[-4 -4]
 [-4 -3]]


 3. Multiply the array with any integers of your choice.

In [ ]:
result1 = x*3
result2=y*3
print(result1)
print(result2)

[[ 3  6]
 [ 9 15]]
[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [ ]:
squared = x ** 2
print(squared)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
v = np.array([9, 10])
w = np.array([11, 12])
dot_vw = np.dot(v, w)
print(dot_vw)

219


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
row_concat = np.concatenate((x, y), axis=0)
print(row_concat)
col_concat = np.column_stack((v, w))
print(col_concat)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
concate_rows=np.concatenate((x, v.reshape(1, 2)), axis=0)
concate_columns=np.concatenate((x, v.reshape(2, 1)), axis=1)
print(concate_rows)
print(concate_columns)

[[ 1  2]
 [ 3  5]
 [ 9 10]]
[[ 1  2  9]
 [ 3  5 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
A = np.array([[3, 4],[7, 8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
import numpy as np

A = np.array([[3, 4],[7, 8]])
B = np.array([[5, 3],[2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB=", AB)
print("BA=", BA)


AB= [[23 13]
 [51 29]]
BA= [[36 44]
 [13 16]]


3. Prove (AB)

T = BTAT

In [ ]:
import numpy as np

A = np.array([[3, 4],[7, 8]])
B = np.array([[5, 3],[2, 1]])

left = np.dot(A, B).T
right = np.dot(B.T, A.T)

print("left =", left)
print("right =", right)
print("equal =", np.array_equal(left, right))


left = [[23 51]
 [13 29]]
right = [[23 51]
 [13 29]]
equal = True


2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9     Solve the following system of Linear equation using Inverse Methods.


In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(X)


[ 2.  1. -2.]
